//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Pizzeria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pizzas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pizzas()
        {
            this.ClientesPizzeria = new HashSet<ClientesPizzeria>();
        }
    
        public int IdPizza { get; set; }
        public string NombreP { get; set; }
        public string Descripcion { get; set; }
        public int Precio { get; set; }
        public string TamañoPizza { get; set; }
        public bool Disponible { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientesPizzeria> ClientesPizzeria { get; set; }
    }
}
